#!/usr/bin/env python3
"""
Fine-tune a small local model into a micro-grid negotiator (LoRA / QLoRA).

STATUS: written, NOT EXECUTED. There is no GPU in the environment this was
authored in, so treat this as a starting point to debug on your own machine
rather than a script known to run clean. The dataset builder it consumes IS
tested and produces verified output.

What this trains
----------------
A LoRA adapter over a 1B-3B base model, on (prompt -> ideal decision) pairs
generated by `build_dataset.py`, where "ideal" comes from an exact LP solver
rather than from a bigger language model. The adapter is a few megabytes and
loads on the same hardware as the base model, which is the whole product thesis:
the expensive part ships once, the domain expertise ships as a small file.

Expected outcome, stated in advance so the result can disprove it
-----------------------------------------------------------------
The binding constraint on 1B models here is format compliance, not economics.
So the prediction is: structured compliance rises sharply (to ~99%) after a few
hundred steps, while allocation efficiency improves much less. If efficiency
does not move at all, the honest conclusion is that a tiny model can learn the
protocol but not the reasoning, and the useful product is a formatter in front
of a classical solver — which is a real finding, not a failure.

Usage
-----
    pip install unsloth trl peft transformers datasets accelerate bitsandbytes
    python finetune/build_dataset.py --synthesize 400 --out data/train.jsonl
    python finetune/train_lora.py --data data/train.jsonl --out adapters/malo-1b

Then serve it through Ollama and benchmark it as another arm:

    # adapters/malo-1b/Modelfile is written for you
    ollama create malo-1b -f adapters/malo-1b/Modelfile
    python benchmark.py --models llama3.2:1b malo-1b \\
        --scenario contended --jitter 0.4 --seeds 30
"""

from __future__ import annotations

import argparse
import json
import os
import sys

MODELFILE = """# Generated by finetune/train_lora.py
FROM {base}
ADAPTER {adapter_path}

PARAMETER temperature 0.15
PARAMETER top_p 0.9
PARAMETER num_predict 260
PARAMETER repeat_penalty 1.1
"""


def main(argv=None) -> int:
    p = argparse.ArgumentParser(
        description="LoRA fine-tune a small model for micro-grid negotiation.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    p.add_argument("--data", default="data/train.jsonl", help="JSONL from build_dataset.py")
    p.add_argument("--val", default=None, help="validation JSONL (defaults to <data>.val.jsonl)")
    p.add_argument("--base", default="unsloth/Llama-3.2-1B-Instruct",
                   help="base model; use unsloth/Qwen2.5-3B-Instruct for the 3B arm")
    p.add_argument("--ollama-base", default="llama3.2:1b",
                   help="the matching Ollama tag, written into the Modelfile")
    p.add_argument("--out", default="adapters/malo-1b")
    p.add_argument("--epochs", type=float, default=2.0)
    p.add_argument("--batch-size", type=int, default=2)
    p.add_argument("--grad-accum", type=int, default=4)
    p.add_argument("--lr", type=float, default=2e-4)
    p.add_argument("--max-seq", type=int, default=2048)
    p.add_argument("--rank", type=int, default=16,
                   help="LoRA rank; 16 is ample for a single narrow task")
    p.add_argument("--load-4bit", action="store_true", default=True,
                   help="QLoRA: fits a 3B fine-tune in roughly 6 GB of VRAM")
    args = p.parse_args(argv)

    if not os.path.exists(args.data):
        print(f"no dataset at {args.data}\n"
              f"run: python finetune/build_dataset.py --synthesize 400 --out {args.data}",
              file=sys.stderr)
        return 2

    try:
        from unsloth import FastLanguageModel
        from unsloth.chat_templates import get_chat_template
        from datasets import load_dataset
        from trl import SFTTrainer, SFTConfig
    except ImportError as exc:
        print(f"missing dependency: {exc}\n"
              "pip install unsloth trl peft transformers datasets accelerate bitsandbytes",
              file=sys.stderr)
        return 2

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=args.base, max_seq_length=args.max_seq,
        load_in_4bit=args.load_4bit, dtype=None)

    # Target every attention and MLP projection: standard for instruction tuning,
    # and cheap at this rank.
    model = FastLanguageModel.get_peft_model(
        model, r=args.rank, lora_alpha=args.rank * 2, lora_dropout=0.0, bias="none",
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        use_gradient_checkpointing="unsloth", random_state=3407)

    tokenizer = get_chat_template(tokenizer, chat_template="llama-3.1")

    def to_text(batch):
        return {"text": [tokenizer.apply_chat_template(m, tokenize=False,
                                                       add_generation_prompt=False)
                         for m in batch["messages"]]}

    val_path = args.val or args.data.replace(".jsonl", ".val.jsonl")
    files = {"train": args.data}
    if os.path.exists(val_path):
        files["validation"] = val_path
    dataset = load_dataset("json", data_files=files)
    dataset = dataset.map(to_text, batched=True)

    trainer = SFTTrainer(
        model=model, tokenizer=tokenizer,
        train_dataset=dataset["train"],
        eval_dataset=dataset.get("validation"),
        args=SFTConfig(
            output_dir=args.out, dataset_text_field="text",
            max_seq_length=args.max_seq,
            per_device_train_batch_size=args.batch_size,
            gradient_accumulation_steps=args.grad_accum,
            num_train_epochs=args.epochs, learning_rate=args.lr,
            warmup_ratio=0.03, lr_scheduler_type="linear",
            logging_steps=10, optim="adamw_8bit", weight_decay=0.01,
            seed=3407, report_to="none"),
    )
    trainer.train()

    os.makedirs(args.out, exist_ok=True)
    model.save_pretrained(args.out)
    tokenizer.save_pretrained(args.out)

    # GGUF export is what Ollama actually loads. If the helper is unavailable,
    # the adapter is still saved and can be converted with llama.cpp by hand.
    try:
        model.save_pretrained_gguf(args.out, tokenizer, quantization_method="q4_k_m")
    except Exception as exc:  # noqa: BLE001
        print(f"GGUF export unavailable ({exc}); adapter saved in HF format only.")

    with open(os.path.join(args.out, "Modelfile"), "w") as fh:
        fh.write(MODELFILE.format(base=args.ollama_base, adapter_path="."))

    print(f"\nadapter written to {args.out}")
    print(f"  ollama create malo-tuned -f {args.out}/Modelfile")
    print( "  python benchmark.py --models "
          f"{args.ollama_base} malo-tuned --scenario contended --jitter 0.4 --seeds 30")
    print("\nThe comparison that matters is structured compliance AND allocation")
    print("efficiency. A jump in the first with none in the second means the model")
    print("learned the format, not the economics — report that plainly.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
