"""
Aurora Research Kit — publication-ready output from an Aurora Bundle.

Generates a directory tree suitable for academic publication:

    research_kit/
      README.md             — orientation: what's in here, how to cite
      methods.md            — full methods section (LaTeX-ready Markdown)
      references.bib        — BibTeX of every prior + every reference
      replication.json      — deterministic re-run config + hashes
      .zenodo.json          — Zenodo deposit metadata (DOI-mintable)
      bundle.aurora.json    — the source bundle this kit was built from

This module is purely additive: it reads an Aurora Bundle (the
``aurora_sdk.Bundle`` artifact built in Phase 1) and writes files. No
network calls, no environment dependencies beyond stdlib.

Design notes:

  * Methods.md is structured around the ``method_registry`` block in
    the bundle, with one subsection per distinct method used. Each
    subsection lists the threshold, the citation, and a one-paragraph
    plain-English description. The bundle's ``assumptions`` list is
    surfaced as a top-level "Assumptions" section.

  * references.bib is generated by transforming the bundle's
    ``method_registry`` keys + any explicit ``seed:*`` citations
    found in findings into BibTeX records. We use a small built-in
    library of canonical citations (Hampel 1974 for robust z-score,
    Liu 2008 for isolation forest, etc.); unknown methods get a
    placeholder ``@misc`` entry the author can fill in.

  * replication.json captures: aurora_version, bundle_hash, dataset
    sha256 (when known), tier, seed, output_root. Anyone with Aurora
    installed and the original dataset can re-run and verify.

  * .zenodo.json is the Zenodo-compatible metadata file. Mint a DOI
    by uploading the research_kit directory to Zenodo.

Security: no shell, no network, no eval. Output is restricted to a
caller-provided directory.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union


# ---------------------------------------------------------------------------
# Built-in citation library — canonical references for methods we know.
# ---------------------------------------------------------------------------
# Each entry maps a normalised method tag to a BibTeX record (no @{...}
# wrapper — added at emit time). Keys are lowercased; lookups are
# substring-tolerant via _normalise_method.
_BUILTIN_CITATIONS: Dict[str, Dict[str, str]] = {
    "robust-z": {
        "key": "hampel1974",
        "type": "article",
        "author": "Hampel, Frank R.",
        "title": "The Influence Curve and Its Role in Robust Estimation",
        "journal": "Journal of the American Statistical Association",
        "year": "1974",
        "volume": "69",
        "number": "346",
        "pages": "383--393",
        "doi": "10.2307/2285666",
    },
    "iso-forest": {
        "key": "liu2008isolation",
        "type": "inproceedings",
        "author": "Liu, Fei Tony and Ting, Kai Ming and Zhou, Zhi-Hua",
        "title": "Isolation Forest",
        "booktitle": "Eighth IEEE International Conference on Data Mining",
        "year": "2008",
        "pages": "413--422",
        "doi": "10.1109/ICDM.2008.17",
    },
    "ar(1)": {
        "key": "hyndman2021forecasting",
        "type": "book",
        "author": "Hyndman, Rob J. and Athanasopoulos, George",
        "title": "Forecasting: principles and practice",
        "publisher": "OTexts",
        "year": "2021",
        "edition": "3rd",
        "url": "https://otexts.com/fpp3/",
    },
    "ar(2)": {
        "key": "hyndman2021forecasting",
        "type": "book",
        "author": "Hyndman, Rob J. and Athanasopoulos, George",
        "title": "Forecasting: principles and practice",
        "publisher": "OTexts",
        "year": "2021",
        "edition": "3rd",
    },
    "granger": {
        "key": "granger1969",
        "type": "article",
        "author": "Granger, C. W. J.",
        "title": "Investigating Causal Relations by Econometric Models and Cross-spectral Methods",
        "journal": "Econometrica",
        "year": "1969",
        "volume": "37",
        "number": "3",
        "pages": "424--438",
        "doi": "10.2307/1912791",
    },
    "hmm_baum_welch": {
        "key": "baumwelch1970",
        "type": "article",
        "author": "Baum, Leonard E. and Petrie, Ted and Soules, George and Weiss, Norman",
        "title": "A Maximization Technique Occurring in the Statistical Analysis of Probabilistic Functions of Markov Chains",
        "journal": "Annals of Mathematical Statistics",
        "year": "1970",
        "volume": "41",
        "number": "1",
        "pages": "164--171",
    },
    "matrix_profile": {
        "key": "yeh2016matrix",
        "type": "inproceedings",
        "author": "Yeh, Chin-Chia Michael and Zhu, Yan and Ulanova, Liudmila and others",
        "title": "Matrix Profile I: All Pairs Similarity Joins for Time Series",
        "booktitle": "IEEE 16th International Conference on Data Mining",
        "year": "2016",
        "pages": "1317--1322",
    },
    "morlet_wavelet": {
        "key": "torrence1998practical",
        "type": "article",
        "author": "Torrence, Christopher and Compo, Gilbert P.",
        "title": "A Practical Guide to Wavelet Analysis",
        "journal": "Bulletin of the American Meteorological Society",
        "year": "1998",
        "volume": "79",
        "number": "1",
        "pages": "61--78",
    },
    "vietoris_rips": {
        "key": "edelsbrunner2010computational",
        "type": "book",
        "author": "Edelsbrunner, Herbert and Harer, John L.",
        "title": "Computational Topology: An Introduction",
        "publisher": "American Mathematical Society",
        "year": "2010",
    },
    "lof": {
        "key": "breunig2000lof",
        "type": "inproceedings",
        "author": "Breunig, Markus M. and Kriegel, Hans-Peter and Ng, Raymond T. and Sander, J{\\\"o}rg",
        "title": "LOF: Identifying Density-based Local Outliers",
        "booktitle": "ACM SIGMOD International Conference on Management of Data",
        "year": "2000",
        "pages": "93--104",
    },
    "mahalanobis_robust": {
        "key": "rousseeuw1999mcd",
        "type": "article",
        "author": "Rousseeuw, Peter J. and Van Driessen, Katrien",
        "title": "A Fast Algorithm for the Minimum Covariance Determinant Estimator",
        "journal": "Technometrics",
        "year": "1999",
        "volume": "41",
        "number": "3",
        "pages": "212--223",
    },
    "gaussian_process": {
        "key": "rasmussen2006gpml",
        "type": "book",
        "author": "Rasmussen, Carl Edward and Williams, Christopher K. I.",
        "title": "Gaussian Processes for Machine Learning",
        "publisher": "MIT Press",
        "year": "2006",
    },
    "mutual_info_ksg": {
        "key": "kraskov2004ksg",
        "type": "article",
        "author": "Kraskov, Alexander and St{\\\"o}gbauer, Harald and Grassberger, Peter",
        "title": "Estimating Mutual Information",
        "journal": "Physical Review E",
        "year": "2004",
        "volume": "69",
        "number": "6",
        "pages": "066138",
    },
}


# Plain-English method descriptions for Methods.md.
_METHOD_DESCRIPTIONS: Dict[str, str] = {
    "robust-z": (
        "Hampel-1974 robust z-score on each numeric column. Per-row "
        "scores compare the value to the column's median absolute "
        "deviation; thresholds of $|z| \\geq 3$ flag a warning and "
        "$|z| \\geq 5$ flag a critical anomaly."
    ),
    "iso-forest": (
        "Isolation Forest (Liu, Ting, \\& Zhou, 2008). Random recursive "
        "partitioning isolates anomalous points faster than dense "
        "ones; the average path length across an ensemble of "
        "isolation trees yields the anomaly score."
    ),
    "ar(1)": (
        "First-order autoregression $y_t = \\phi y_{t-1} + b + \\epsilon_t$ "
        "fitted by ordinary least squares. Confidence intervals "
        "propagate analytically: $\\sigma_{t+1}^2 = (1 + \\phi \\Delta t)^2 \\sigma_t^2$."
    ),
    "granger": (
        "Granger causality test (Granger, 1969). Compares the "
        "predictive RSS of $Y$ given $Y_{<t}$ versus $Y_{<t} \\cup X_{<t}$; "
        "rejection at $p < 0.05$ indicates $X$ helps predict $Y$ beyond "
        "$Y$'s own past."
    ),
    "hmm_baum_welch": (
        "Hidden Markov Model fit via Baum-Welch EM (Baum et al., 1970). "
        "Latent state count $k$ selected by BIC; emissions are "
        "Gaussian per state."
    ),
    "matrix_profile": (
        "Matrix profile (Yeh et al., 2016). For each subsequence of "
        "length $w$, the distance to its nearest non-trivial neighbour. "
        "Minima locate motifs (recurring shapes); maxima locate "
        "discords (one-off events)."
    ),
    "morlet_wavelet": (
        "Continuous wavelet transform with the Morlet mother wavelet "
        "(Torrence \\& Compo, 1998). Ridges in the scalogram identify "
        "persistent periodic structure across scales."
    ),
    "vietoris_rips": (
        "Vietoris-Rips persistent homology (Edelsbrunner \\& Harer, 2010). "
        "Filtration on $\\epsilon$-balls around data points produces a "
        "persistence diagram; $H_0$ (components) and $H_1$ (1-cycles) "
        "are extracted from the diagram's most-persistent bars."
    ),
    "lof": (
        "Local Outlier Factor (Breunig et al., 2000). Density-based "
        "score: ratio of a point's local reachability density to that "
        "of its $k$-nearest neighbours."
    ),
    "mahalanobis_robust": (
        "Mahalanobis distance with the Minimum Covariance Determinant "
        "estimator (Rousseeuw \\& Van Driessen, 1999). Robust to up to "
        "$\\sim 25\\%$ contamination."
    ),
    "gaussian_process": (
        "Gaussian process regression with the radial basis kernel "
        "(Rasmussen \\& Williams, 2006). Hyperparameters fit by "
        "maximising the log-marginal likelihood."
    ),
    "mutual_info_ksg": (
        "Kraskov-St\\\"ogbauer-Grassberger non-parametric mutual "
        "information estimator (Kraskov et al., 2004). $k$-nearest-"
        "neighbour distances on the joint and marginal samples."
    ),
}


def _normalise_method(name: str) -> str:
    """Lowercase + strip + simplify a method tag to its citation key.

    Returns the FIRST matched citation key (used by methods.md for the
    inline ``[key]`` tag). For full citation emission (in the bib
    file), use ``_match_methods`` which returns every match.
    """
    n = str(name or "").lower().strip()
    for k in _BUILTIN_CITATIONS:
        if k in n:
            return k
    return n


def _match_methods(name: str) -> List[str]:
    """Return EVERY citation key that appears in the given method tag.

    Combined tags like "ISO-FOREST + ROBUST-Z" deserve both citations
    in references.bib; this is the multi-match resolver that supports
    that. Order preserves _BUILTIN_CITATIONS insertion order.
    """
    n = str(name or "").lower().strip()
    return [k for k in _BUILTIN_CITATIONS if k in n]


# ---------------------------------------------------------------------------
# Generators
# ---------------------------------------------------------------------------

def _bibtex_record(rec: Dict[str, str]) -> str:
    """Render a single BibTeX entry."""
    bibtype = rec.get("type") or "misc"
    key = rec.get("key") or "anon"
    body_keys = [k for k in rec.keys() if k not in ("type", "key")]
    lines = [f"@{bibtype}{{{key},"]
    for k in body_keys:
        v = rec[k]
        if v is None:
            continue
        lines.append(f"  {k} = {{{v}}},")
    # Remove trailing comma from last line for cleanliness.
    if lines[-1].endswith(","):
        lines[-1] = lines[-1][:-1]
    lines.append("}")
    return "\n".join(lines)


def generate_references_bib(bundle: Dict[str, Any]) -> str:
    """Build a BibTeX file from the bundle's method_registry + any
    inline ``seed:*`` citations in findings.

    Unknown methods get a placeholder ``@misc{aurora-<slug>, ...}``
    entry the author can fill in.
    """
    used: List[Dict[str, str]] = []
    seen_keys: set = set()

    # 1. Citations for every method that appeared in findings.
    #    Combined tags (e.g., "ISO-FOREST + ROBUST-Z") yield multiple
    #    citations — see _match_methods.
    registry = bundle.get("method_registry") or {}
    for method_name in registry.keys():
        matches = _match_methods(method_name)
        if matches:
            for key in matches:
                rec = _BUILTIN_CITATIONS[key]
                if rec["key"] not in seen_keys:
                    used.append(rec)
                    seen_keys.add(rec["key"])
        else:
            slug = "".join(
                c if c.isalnum() else "-" for c in str(method_name).lower()
            ).strip("-")[:48] or "anon"
            placeholder_key = f"aurora-{slug}"
            if placeholder_key not in seen_keys:
                used.append({
                    "key": placeholder_key,
                    "type": "misc",
                    "author": "Aurora-QIE (method tag, fill in)",
                    "title": str(method_name),
                    "year": str(datetime.now(timezone.utc).year),
                    "note": "Method tag emitted by Aurora; fill in canonical citation.",
                })
                seen_keys.add(placeholder_key)

    # 2. Aurora itself.
    aurora_v = bundle.get("aurora_version") or "unknown"
    if "aurora-qie" not in seen_keys:
        used.append({
            "key": "aurora-qie",
            "type": "software",
            "title": "Aurora-QIE: Quantitative Intelligence Console",
            "author": "Aurora-QIE Contributors",
            "version": aurora_v,
            "year": str(datetime.now(timezone.utc).year),
            "url": "https://aurora-qie.dev",
            "note": "Local-first glass-box quantitative analysis tool.",
        })
        seen_keys.add("aurora-qie")

    return "\n\n".join(_bibtex_record(r) for r in used) + "\n"


def generate_methods_md(bundle: Dict[str, Any]) -> str:
    """Produce a journal-ready Methods.md section.

    Structure:
      # Methods
      ## Data
      ## Pipeline overview
      ## Methods used
        ### <Method 1>
        ...
      ## Assumptions
      ## Confidence
      ## Reproducibility
    """
    ds = bundle.get("dataset") or {}
    struct = bundle.get("structure") or {}
    sm = bundle.get("system_model") or {}
    aurora_v = bundle.get("aurora_version") or "unknown"
    run = bundle.get("run") or {}
    integ = bundle.get("integrity") or {}
    assumptions = bundle.get("assumptions") or []
    registry = bundle.get("method_registry") or {}

    def _esc(s: Any) -> str:
        return str(s).replace("_", "\\_") if s is not None else "—"

    lines: List[str] = []
    lines.append("# Methods\n")
    lines.append(
        f"_All analyses were performed with Aurora-QIE v{aurora_v} "
        f"(bundle hash: `{integ.get('content_hash', 'n/a')}`). All "
        f"thresholds and citations below reflect Aurora's "
        f"glass-box defaults; no findings were generated by an LLM._\n"
    )

    # Data
    lines.append("## Data\n")
    lines.append(
        f"The input dataset (`{_esc(ds.get('basename') or ds.get('name'))}`) "
        f"contains {ds.get('rows', '?')} rows and {ds.get('cols', '?')} "
        f"columns "
        f"({'with' if struct.get('time_axis') else 'without'} a regular "
        f"time axis"
        + (f", cadence {_esc(struct.get('cadence'))}" if struct.get('time_axis') else "")
        + ").\n"
    )
    if ds.get("sha256"):
        lines.append(
            f"The dataset SHA-256 hash is `{ds['sha256']}`. "
            "Including this in your supplementary material allows "
            "readers to verify the exact file analysed.\n"
        )

    # Pipeline overview
    lines.append("## Pipeline overview\n")
    tier = run.get("tier") or "auto"
    lines.append(
        f"Aurora was run at depth `{tier}`, which executes tier-1 "
        f"(anomaly + regime + motif + AR baseline forecast) followed by "
        f"tier-2 (Bayesian, Granger, Gaussian process, wavelet, "
        f"topology) and, when `full`, tier-3 (full-data replication). "
        f"Every finding is tagged with the method that produced it, "
        f"the threshold applied, and a citation; findings without "
        f"complete provenance are flagged `fabricated`.\n"
    )

    # Methods used
    lines.append("## Methods used\n")
    if not registry:
        lines.append("_No method-tagged findings in this run._\n")
    for method_name, rec in registry.items():
        count = rec.get("count", 0)
        sevs = rec.get("severities") or {}
        sev_str = ", ".join(f"{k}={v}" for k, v in sevs.items()) or "—"
        normal = _normalise_method(method_name)
        cite = _BUILTIN_CITATIONS.get(normal)
        cite_inline = f" [{cite['key']}]" if cite else ""
        lines.append(f"### {method_name}{cite_inline}\n")
        lines.append(
            f"- Findings produced: {count} ({sev_str})\n"
        )
        desc = _METHOD_DESCRIPTIONS.get(normal)
        if desc:
            lines.append(desc + "\n")
        else:
            lines.append(
                "_Plain-English description not yet curated for this "
                "method tag — fill in for camera-ready._\n"
            )

    # Assumptions
    lines.append("## Assumptions\n")
    if assumptions:
        for a in assumptions:
            lines.append(f"- {a}\n")
    else:
        lines.append("_No assumptions explicitly declared in this run._\n")

    # Confidence
    conf = sm.get("confidence")
    lines.append("## Confidence\n")
    if conf is not None:
        pct = round(float(conf) * 100)
        tier_label = ("strong (template anchored)" if pct >= 60
                      else "moderate (partial anchoring)" if pct >= 30
                      else "low (mostly inferred)")
        lines.append(
            f"The overall system-model confidence is **{pct}%** "
            f"({tier_label}). Confidence reflects the slot-fill rate of "
            f"the matched domain template multiplied by the strength of "
            f"the discovered relationships and the satisfaction of "
            f"declared constraints.\n"
        )
    else:
        lines.append("_System-model confidence not available._\n")

    # Reproducibility
    lines.append("## Reproducibility\n")
    lines.append(
        f"All analyses are reproducible from the accompanying "
        f"`replication.json` and the source dataset. Re-running "
        f"Aurora-QIE v{aurora_v} on the same file should yield a "
        f"bundle whose content hash matches "
        f"`{integ.get('content_hash', 'n/a')}` exactly. Floating-point "
        f"non-determinism in some advanced methods (e.g., Gaussian "
        f"process MCMC sampling, when enabled) may produce numerically "
        f"close but not bit-identical results; tier-1 statistics are "
        f"fully deterministic.\n"
    )

    return "".join(lines)


def generate_replication_json(bundle: Dict[str, Any]) -> Dict[str, Any]:
    """Deterministic re-run config.

    Captures every input a third party needs to reproduce this run.
    """
    ds = bundle.get("dataset") or {}
    run = bundle.get("run") or {}
    integ = bundle.get("integrity") or {}
    return {
        "schema": "aurora.replication/v1",
        "aurora_version": bundle.get("aurora_version"),
        "bundle_hash": integ.get("content_hash"),
        "dataset": {
            "basename": ds.get("basename"),
            "sha256": ds.get("sha256"),
            "rows": ds.get("rows"),
            "cols": ds.get("cols"),
            "size_mb": ds.get("size_mb"),
        },
        "run": {
            "id": run.get("run_id"),
            "tier": run.get("tier") or "auto",
            "started_at": run.get("started_at"),
            "completed_at": run.get("completed_at"),
        },
        "instructions": [
            "1. Install Aurora-QIE at the version listed above.",
            "2. Obtain the dataset file matching the listed SHA-256.",
            "3. Run: `aurora analyze <dataset> --depth <tier>`",
            "4. Verify the new bundle's content_hash matches bundle_hash above.",
            "   Bit-identical for tier-1; numerically close for tier-2/3 advanced methods.",
        ],
    }


def generate_zenodo_json(bundle: Dict[str, Any],
                         *,
                         title: Optional[str] = None,
                         creators: Optional[List[Dict[str, str]]] = None,
                         keywords: Optional[List[str]] = None,
                         description: Optional[str] = None,
                         ) -> Dict[str, Any]:
    """Zenodo deposit metadata. Mint a DOI by uploading the kit directory
    to Zenodo with this file at the root.

    See https://developers.zenodo.org/#representation for the schema.
    """
    run = bundle.get("run") or {}
    ds = bundle.get("dataset") or {}
    sm = bundle.get("system_model") or {}
    integ = bundle.get("integrity") or {}

    default_title = (
        title or
        f"Aurora-QIE analysis of {ds.get('basename') or 'dataset'} "
        f"(run {run.get('run_id') or 'unknown'})"
    )
    default_desc = (description or
        "Aurora-QIE quantitative analysis bundle, including findings, "
        "methods, assumptions, and a cryptographically-hashed "
        "reproducibility manifest. The accompanying methods.md is "
        "publication-ready; references.bib lists every cited prior. "
        "Aurora-QIE bundle hash: " + str(integ.get("content_hash") or "n/a")
    )
    return {
        "metadata": {
            "title": default_title,
            "description": default_desc,
            "creators": creators or [{"name": "Aurora-QIE User"}],
            "keywords": keywords or [
                "Aurora-QIE",
                "quantitative analysis",
                "anomaly detection",
                "reproducible research",
                "glass-box AI",
            ],
            "upload_type": "dataset",
            "publication_date": (run.get("completed_at") or "").split("T")[0]
                                  or datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            "access_right": "open",
            "license": "CC-BY-4.0",
            "notes": (
                f"Generated by aurora_sdk research_kit. Aurora-QIE v"
                f"{bundle.get('aurora_version') or 'unknown'}. "
                f"Findings produced: "
                f"{sum((r.get('count', 0) for r in (bundle.get('method_registry') or {}).values()), 0)}. "
                f"Confidence: {round((sm.get('confidence') or 0) * 100)}%."
            ),
            "related_identifiers": [
                {
                    "scheme": "url",
                    "identifier": "https://aurora-qie.dev",
                    "relation": "isDerivedFrom",
                    "resource_type": "software",
                },
            ],
        }
    }


def generate_readme(bundle: Dict[str, Any]) -> str:
    """Top-level README orienting the reviewer/author."""
    run = bundle.get("run") or {}
    ds = bundle.get("dataset") or {}
    integ = bundle.get("integrity") or {}
    return (
        f"# Aurora-QIE Research Kit\n\n"
        f"This directory is a publication-ready bundle of an Aurora "
        f"quantitative analysis.\n\n"
        f"## Contents\n\n"
        f"- `methods.md` — full methods section, ready to paste into a "
        f"paper (Markdown, LaTeX math)\n"
        f"- `references.bib` — BibTeX entries for every prior cited in "
        f"the methods\n"
        f"- `replication.json` — deterministic re-run config + bundle "
        f"hash for verification\n"
        f"- `.zenodo.json` — Zenodo deposit metadata for DOI minting\n"
        f"- `bundle.aurora.json` — the source bundle this kit was "
        f"generated from\n\n"
        f"## Identifying this run\n\n"
        f"- Aurora-QIE version: `{bundle.get('aurora_version') or 'unknown'}`\n"
        f"- Run ID: `{run.get('run_id') or 'unknown'}`\n"
        f"- Dataset: `{ds.get('basename') or ds.get('name') or 'unknown'}`"
        f" ({ds.get('rows', '?')} × {ds.get('cols', '?')})\n"
        f"- Bundle content hash: `{integ.get('content_hash') or 'n/a'}`\n\n"
        f"## How to cite\n\n"
        f"Cite Aurora-QIE itself using the `aurora-qie` entry in "
        f"`references.bib`. Each method used in this run has its own "
        f"BibTeX entry — cite those alongside.\n\n"
        f"## Verifying integrity\n\n"
        f"With Aurora-QIE installed:\n\n"
        f"```python\n"
        f"from aurora_sdk import Bundle\n"
        f"b = Bundle.load(\"bundle.aurora.json\")\n"
        f"b.verify()   # raises if tampered\n"
        f"```\n\n"
        f"## License\n\n"
        f"By default the kit is published under CC-BY-4.0 (see `.zenodo.json`)."
        f" Edit `.zenodo.json` before uploading if a different license "
        f"applies to your data.\n"
    )


# ---------------------------------------------------------------------------
# Top-level entrypoint: write the kit
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ResearchKitPaths:
    """Where each kit file lives. Returned by ``write_research_kit``."""
    root: Path
    readme: Path
    methods: Path
    bib: Path
    replication: Path
    zenodo: Path
    bundle: Path


def write_research_kit(bundle: Dict[str, Any],
                        output_dir: Union[str, Path],
                        *,
                        title: Optional[str] = None,
                        creators: Optional[List[Dict[str, str]]] = None,
                        keywords: Optional[List[str]] = None,
                        description: Optional[str] = None,
                        overwrite: bool = False,
                        ) -> ResearchKitPaths:
    """Write the kit to ``output_dir``. Creates the directory if it
    doesn't exist. Refuses to overwrite existing files unless
    ``overwrite=True``."""
    out = Path(output_dir).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)

    files = {
        "README.md":          generate_readme(bundle),
        "methods.md":         generate_methods_md(bundle),
        "references.bib":     generate_references_bib(bundle),
        "replication.json":   json.dumps(
            generate_replication_json(bundle), indent=2, ensure_ascii=False
        ),
        ".zenodo.json":       json.dumps(
            generate_zenodo_json(bundle, title=title, creators=creators,
                                  keywords=keywords, description=description),
            indent=2, ensure_ascii=False,
        ),
        "bundle.aurora.json": json.dumps(bundle, indent=2, ensure_ascii=False,
                                          default=str),
    }
    for fname, content in files.items():
        target = out / fname
        if target.exists() and not overwrite:
            raise FileExistsError(
                f"{target} exists; pass overwrite=True to replace"
            )
        target.write_text(content, encoding="utf-8")

    return ResearchKitPaths(
        root=out,
        readme=out / "README.md",
        methods=out / "methods.md",
        bib=out / "references.bib",
        replication=out / "replication.json",
        zenodo=out / ".zenodo.json",
        bundle=out / "bundle.aurora.json",
    )
